name = "AdventOfCode"
uuid = "ec480b64-8d68-453c-9e84-9dbf6ce847d6"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn>"]
version = "0.1.0"

[deps]
Alpine = "07493b3f-dabb-5b16-a503-4139292d7dd4"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Mods = "7475f97c-0381-53b1-977b-4c60186c8d62"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
